doc-warnings: true
test-warnings: false
strictness: high
max-line-length: 120
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - contrib
python-targets:
  - 2
  - 3
